version: "3.8"
services:
  db:
    image: bence/postgres-normal
    ports:
      - 5432:5432
  db-admin:
    image: dpage/pgadmin4
    ports:
      - 8079:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=nembence1994@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
