amusement-park.transaction-logging: true
spring:
  jmx.enabled: false
  datasource.platform: h2
  jpa:
    open-in-view: false
    show-sql: true
    properties.hibernate.format_sql: true
  session.store-type: jdbc
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
---

amusement-park.transaction-logging: false
spring:
  profiles: postgres
  jmx.enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/amusement_park
    username: postgres
    password: admin
    platform: postgresql
    initialization-mode: never
  jpa:
    open-in-view: false
    show-sql: false
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  session:
    store-type: jdbc
    jdbc.initialize-schema: never
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: false

---

amusement-park.transaction-logging: false
spring:
  profiles: docker
  jmx.enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/amusement_park
    username: postgres
    password: admin
    initialization-mode: never
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: false